# Welcome to Jekyll!
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Coding-Steve's Blog
email: tyrinteractivestudios@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  My first blog, the place where I plan on writing things down. I don't expect
  anyone to actually read it, but maybe someone will stumble their way here once
  in awhile and find something they find interesting.

github_username:  StevenPG
linkedin_username: test

# For now until I get a dedicated site up and running
url: "https://stevenpg.com" # the base hostname & protocol for your site, e.g. http://example.com

# Google Analytics
google_analytics: G-2ZPXM6LPR3

home_post_limit: 5

# Build settings
remote_theme: jekyll/minima
gravatar_hash: 2136e716a089f4a3794f4007328c7bfb
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-sitemap

# Used by simple links page
social-links:
  LinkedIn:        https://linkedin.com/in/abc123
  StackOverflow:   https://stackoverflow.com/users/abc123
  GitHub:          https://github.com/abc123
  Website:         https://howoldaremycats.com

social:
  name: Steve
  links:
    - https://linkedin.com/in/abc123
    - https://github.com/abc123

collections:
  personal: # collection for personal blog posts
    output: true